@startuml

skin rose

entity Account {
  * id: uuid
  --
  * firstName: string
  * surname: string
  * email: string @unique
  * passwordHash: string
  * avatar: string
  * createdAt: datetime
  * updatedAt: datetime
  deletedAt: datetime
}

entity Post {
  * id: uuid
  --
  * jobName: string
  * description: string
  * wage: float
  * location: string
  * expectedHours: float
  * createdAt: datetime
  * updatedAt: datetime
  deletedAt: datetime
}

entity CV {
  * id: uuid
  --
  * fileName: string
  * fileType: string
  * fileSize: int
  * fileContent: bytes  
  * createdAt: datetime
  * updatedAt: datetime
  deletedAt: datetime
}

Account ||--o{ Post : creates 

Account }o--o{ Post : applies

Account ||--o| CV : has

@enduml
